Repository nasa/hybridq, pull requests merged in 2021-11, with the labels that each got.

#43 Update copyright
  LICENSE
Labels: documentation

#46 Remove old packages
  packages/hybridq-0.7.7.post2-py3-none-manylinux2010_x86_64.whl
  packages/hybridq-0.7.7.post2-py3-none-manylinux2014_x86_64.whl
  packages/hybridq-0.7.7.post5-cp37-cp37m-macosx_10_9_x86_64.whl
  packages/hybridq-0.7.7.post5-py3-none-manylinux2010_x86_64.whl
  packages/hybridq-0.7.7.post5-py3-none-manylinux2014_x86_64.whl
Labels: post-fixes

#48 Add `LGTM` badges
  README.md
Labels: enhancement, GitHub

#20 Add tutorial on the use of `Gate`s in `HybridQ`
  README.md
  examples/SC21/SC21_noise_figs_Sect_VI.ipynb
  hybridq/noise/channel/channel.py
  hybridq/noise/channel/utils.py
  tutorials/00_installation.ipynb
  tutorials/01_gates.ipynb
  tutorials/XX_noise.ipynb
Labels: documentation

#55 Enable MyBinder in `HybridQ`
  .github/python-pytest.yml.__base__
  .github/workflows/pre-release.yml
  .github/workflows/python-example.yml
  .github/workflows/python-format.yml
  .github/workflows/python-pytest_circuit_cp37-cp37m.yml
  .github/workflows/python-pytest_circuit_cp38-cp38.yml
  .github/workflows/python-pytest_circuit_utils_cp37-cp37m.yml
  .github/workflows/python-pytest_circuit_utils_cp38-cp38.yml
  .github/workflows/python-pytest_cliffords_cp37-cp37m.yml
  .github/workflows/python-pytest_cliffords_cp38-cp38.yml
  .github/workflows/python-pytest_dm_0_cp37-cp37m.yml
  .github/workflows/python-pytest_dm_0_cp38-cp38.yml
  .github/workflows/python-pytest_dm_1_cp37-cp37m.yml
  .github/workflows/python-pytest_dm_1_cp38-cp38.yml
  .github/workflows/python-pytest_dm_2_cp37-cp37m.yml
  .github/workflows/python-pytest_dm_2_cp38-cp38.yml
  .github/workflows/python-pytest_dm_3_cp37-cp37m.yml
  .github/workflows/python-pytest_dm_3_cp38-cp38.yml
  .github/workflows/python-pytest_gate_utils_cp37-cp37m.yml
  .github/workflows/python-pytest_gate_utils_cp38-cp38.yml
  .github/workflows/python-pytest_gates_cp37-cp37m.yml
  .github/workflows/python-pytest_gates_cp38-cp38.yml
  .github/workflows/python-pytest_noise_1_cp37-cp37m.yml
  .github/workflows/python-pytest_noise_1_cp38-cp38.yml
  .github/workflows/python-pytest_simulation_1_cp37-cp37m.yml
  .github/workflows/python-pytest_simulation_1_cp38-cp38.yml
  .github/workflows/python-pytest_simulation_2_cp37-cp37m.yml
  .github/workflows/python-pytest_simulation_2_cp38-cp38.yml
  .github/workflows/python-pytest_simulation_3_cp37-cp37m.yml
  .github/workflows/python-pytest_simulation_3_cp38-cp38.yml
  .github/workflows/python-pytest_simulation_4_cp37-cp37m.yml
  .github/workflows/python-pytest_simulation_4_cp38-cp38.yml
  .github/workflows/python-pytest_simulation_5_cp37-cp37m.yml
  .github/workflows/python-pytest_simulation_5_cp38-cp38.yml
  .github/workflows/python-pytest_utils_cp37-cp37m.yml
  .github/workflows/python-pytest_utils_cp38-cp38.yml
  Dockerfile
  Dockerfile_baseline
  README.md
  scripts/generate_containers.sh
Labels: enhancement, GitHub, post-fixes

#53 Add docstring to `NamedGate`s
  hybridq/base/property.py
  hybridq/gate/gate.py
  hybridq/gate/property.py
Labels: documentation, post-fixes

#54 Move documentation from `docs/html/hybridq` --> `docs/`
  docs/architecture/index.html
  docs/architecture/plot.html
  docs/architecture/sycamore.html
  docs/base/base.html
  docs/base/index.html
  docs/base/property.html
  docs/circuit/circuit.html
  docs/circuit/index.html
  docs/circuit/simulation/clifford.html
  docs/circuit/simulation/index.html
  docs/circuit/simulation/simulation.html
  docs/circuit/simulation/simulation_mpi.html
  docs/circuit/simulation/utils.html
  docs/circuit/utils.html
  docs/dm/circuit/circuit.html
  docs/dm/circuit/index.html
  docs/dm/circuit/simulation.html
  docs/dm/gate/gate.html
  docs/dm/gate/index.html
  docs/dm/gate/property.html
  docs/dm/gate/utils.html
  docs/dm/index.html
  docs/extras/architecture/index.html
  docs/extras/architecture/plot.html
  docs/extras/architecture/sycamore.html
  docs/extras/gate/gate.html
  docs/extras/gate/index.html
  docs/extras/index.html
  docs/extras/io/cirq.html
  docs/extras/io/index.html
  docs/extras/io/qasm.html
  docs/extras/random.html
  docs/extras/simulation/index.html
  docs/extras/simulation/otoc.html
  docs/gate.html
  docs/gate/gate.html
  docs/gate/index.html
  docs/gate/measure.html
  docs/gate/projection.html
  docs/gate/property.html
  docs/gate/utils.html
  docs/index.html
  docs/noise/channel/channel.html
  docs/noise/channel/index.html
  docs/noise/channel/utils.html
  docs/noise/index.html
  docs/noise/utils.html
  docs/utils.html
  docs/utils/aligned/aligned_array.html
  docs/utils/aligned/index.html
  docs/utils/dot.html
  docs/utils/index.html
  docs/utils/transpose.html
  docs/utils/utils.html
  scripts/generate_documentation.sh
Labels: documentation, post-fixes

#58 Check Tutorials
  .github/workflows/python-tutorials.yml
Labels: GitHub, post-fixes

#59 Improve `StochasticGate`
  hybridq/gate/gate.py
  hybridq/gate/property.py
Labels: enhancement, post-fixes

#73 Update README.md
  README.md
Labels: documentation

#67 Fix hashbangs
  .github/workflows/python-format.yml
  scripts/check_format.sh
  scripts/check_prerequisite.sh
  scripts/generate_documentation.sh
Labels: bug

#63 Add support for `StochasticGate`'s and `FunctionalGate`'s
  .github/workflows/python-tutorials.yml
  Dockerfile
  hybridq/circuit/simulation/simulation.py
  hybridq/noise/channel/channel.py
  hybridq/noise/channel/utils.py
  hybridq/utils/utils.py
  tests/tests.py
  tutorials/XX_noise.ipynb
Labels: enhancement, post-fixes

#78 Update `README.md`
  README.md
Labels: documentation

#80 Circuit: Add `__iadd__`
  hybridq/circuit/circuit.py
  tests/tests.py
Labels: bug
