Repository nasa/hybridq, pull requests merged in 2021-10, with the labels that each got.

#2 Fix Docker + GitHub Actions
  .github/python-pytest.yml.__base__
  .github/workflows/pre-release.yml
  .github/workflows/python-example.yml
  .github/workflows/python-format.yml
  .github/workflows/python-pytest_test_circuit.yml
  .github/workflows/python-pytest_test_cliffords.yml
  .github/workflows/python-pytest_test_dm.yml
  .github/workflows/python-pytest_test_gates.yml
  .github/workflows/python-pytest_test_simulation.yml
  .github/workflows/python-pytest_test_utils.yml
  Dockerfile_baseline
  README.md
Labels: bug

#3 Upload packages to `PyPI`
  README.md
  packages/Dockerfile
  packages/hybridq-0.5.1-cp37-cp37m-macosx_10_9_x86_64.whl
  packages/hybridq-0.5.1-py3-none-manylinux2010_x86_64.whl
  packages/hybridq-0.5.1-py3-none-manylinux2014_x86_64.whl
  packages/hybridq-0.7.5-py3-none-manylinux2010_x86_64.whl
  packages/hybridq-0.7.5-py3-none-manylinux2014_x86_64.whl
  packages/hybridq-0.7.6-py3-none-manylinux2010_x86_64.whl
  packages/hybridq-0.7.6-py3-none-manylinux2014_x86_64.whl
  scripts/generate_packages.sh
  setup.py
Labels: enhancement

#12 Fix consistency for `KrausSuperGate` left and right `Gate`s
  hybridq/dm/gate/gate.py
  hybridq/gate/gate.py
  hybridq/gate/property.py
  setup.py
Labels: bug

#15 Fix `__Base__.__eq__`
  hybridq/base/base.py
  setup.py
Labels: bug

#14 Noise Utilities
  .github/workflows/python-pytest_noise_1.yml
  .gitignore
  hybridq/noise/channel/__init__.py
  hybridq/noise/channel/channel.py
  hybridq/noise/utils.py
  tests/tests.py
Labels: enhancement

#21 Small fixes
  hybridq/circuit/utils.py
  hybridq/extras/random.py
  hybridq/gate/gate.py
  hybridq/gate/property.py
  hybridq/gate/utils.py
  hybridq/noise/channel/channel.py
  hybridq/utils/utils.py
  tests/tests.py
Labels: bug, enhancement
